### ISSUE TITLE
script to test my own images

### ISSUE THREAD

**Issue by kaishijeng** [lucastabelini/PolyLaneNet#2]
Do you have python script which can be used to test my own images?
I tried to modify test.py, but without any success.

Thanks,

**Comment by lucastabelini** [comment]
If you only want qualitative results (i.e., you don't want to compute metrics), you can use the `NoLabelDataset` class. To use it on one of the pretrained models, you can copy its config file (`.yaml`) and change the dataset settings. In the dataset settings section of this file, you can set the test dataset like this (leaving the rest as it is):

```yaml
  test: &test
    type: LaneDataset
    parameters:
      dataset: nolabel_dataset
      normalize: true # Wheter to normalize the input data. Use the same value used in the pretrained model (all pretrained models that I provided used normalization, so you should leave it as it is)
      augmentations: [] # List of augmentations. You probably want to leave this empty for testing
      img_h: 360 # The height of your test images (they shoud all have the same size)
      img_w: 640 # The width of your test images
      img_size: [360, 640] # Yeah, this parameter is duplicated for some reason, will fix this when I get time (feel free to open a pull request :))
      max_lanes: 5 # Same number used in the pretrained model. If you use a model pretrained on TuSimple (most likely case), you'll use 5 here
      root: "path/to/files" # Path to the directory containing your test images. The loader will look recursively for image files in this directory
      img_ext: ".jpg" # Test images extension (e.g., .png, .jpg)"
```

During the test, when running the `test.py` script, you can use the flag `--view` to visualize predictions.

If you want quantitative results too (i.e., metrics), you will have to implement a loader for your dataset. If that's the case, feel free to ask for help on that.
